services:
  
  dev-db:
    image: postgres:16.4-alpine3.20
    restart: always
    ports:
      - 5532:5432
    env_file:
      - ./.env
    volumes:
      # access initialization scripts at the container with postgres image:
      - ./scripts:/docker-entrypoint-initdb.d
    

  adminer:
    image: adminer
    restart: always
    ports:
      - 8082:8080
