"""unique

Revision ID: bc163cf8117b
Revises: 3a378a9da599
Create Date: 2024-10-13 01:05:49.088495

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc163cf8117b'
down_revision: Union[str, None] = '3a378a9da599'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_category_name_level', 'category', ['name', 'level'])
    op.create_unique_constraint('uq_category_slug', 'category', ['slug'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_category_slug', 'category', type_='unique')
    op.drop_constraint('uq_category_name_level', 'category', type_='unique')
    # ### end Alembic commands ###
